### ISSUE TITLE
Different Sigma for 'belief' and 'constant' versions

### ISSUE THREAD

**Issue by evanatyourservice** [XuezheMax/apollo#8]
Hello! Thank you so much for this work! I've had great luck with it and am making an implementation in tf2.

I have a question about this line:

https://github.com/XuezheMax/apollo/blob/852991fd769f80689415abee8653c0a5eedbab40/optim/apollo.py#L111

Is there a benefit to keeping sigma = 1.0 for the 'belief' version, or should I make it 0.01 to match the 'constant' version?

**Comment by XuezheMax** [comment]
Hello,
Thanks for your interests! As stated in the paper and repo, we changed `sigma` from `1.0` to `0.01` to make its learning rate in a suitable range. For the `belief` version, we found that with `sigma=1.0` the learning rates are already in a suitable range, like `0.01`. So we did not change it to 0.01 as we did in the `constant` version. 

To be honest, we have not fully tuned the `belief` version, because it is an extension of the main Apollo algorithm.

**Comment by evanatyourservice** [comment]
Excellent, thank you so much for your response! I figured this was the case but wanted to double check. Have a nice week!

**Comment by evanatyourservice** [comment]
https://github.com/evanatyourservice/Apollo-tf

**Comment by XuezheMax** [comment]
Thank you!
